spring:
  datasource:
    url: jdbc:h2:~/redey
    username: redey
    password: redey
    driverclassname: org.h2.Driver
    platform: h2
    
  jpa:
    properties:
      eclipselink.ddl-generation.output-mode: sql-script
      eclipselink.ddl-generation: create-tables

server:
  port: 8092
  compression:
    enabled: true
    
endpoints:
    sensitive: false
management:
    context-path: /manage
    security: 
        enabled: false

game:
  rest:
    url: http://game:8091/game/

user:
  rest:
    url: http://user:8092/user/